### ISSUE TITLE
May I ask if this feature is currently available?

### ISSUE THREAD

**Issue by CommenVillager** [saul/cvar-unhide-s2#1]
Hello sir, may I ask if this is a completed function? I do not see any downloadable files in the website you provided below     https://github.com/saul/cvar-unhide-s2/releases/latest

**Comment by saul** [comment]
The addon isn't yet available as a downloadable yet. The source is here for developers familiar with Source to be able to compile themselves.

A downloadable addon will be available when the reverse-engineered Source 2 SDK is available. There's an open PR that GAMMACASE and others are working on here: https://github.com/alliedmodders/hl2sdk/pull/125

Reverse engineering will take time, but when it's done this addon will be available. Your patience is appreciated 😄

**Comment by saul** [comment]
A version is available for download now. Thank you for waiting
