### ISSUE TITLE
-insecure

### ISSUE THREAD

**Issue by armync** [saul/cvar-unhide-s2#2]
~~How safe is this addons as we speaking? I mean that the Launch Option -insecure wasn't working. I didn't get any in-game warning and I also played a matchmaking with it set (not talking about cvar-unhider, just the launch option).~~

EDIT: Now the flag is working, maybe a (typing) mistake on my side.

Thanks!

**Comment by saul** [comment]
For anyone else who stumbles upon this issue:

The addon will refuse to load before you even get to the main menu if `-insecure` is not set. It is impossible to have this addon loaded in memory and have VAC running at the same time (which only starts when you join a VAC secure server).

**Comment by armync** [comment]
That is right. My stupid mistake was that I thought Valve had removed/broke that flag in the build, rendering the set flag check useless.
