### ISSUE TITLE
Console log

### ISSUE THREAD

**Issue by armync** [saul/cvar-unhide-s2#3]
Right now, I'm unable to extract all the commands from the console using _cvar_unhide_ followed by _cvarlist_. **con_logfile** is deprecated. Is there any other way or could you implement a log?

**Comment by saul** [comment]
I will consider adding a `cvarlist` command that logs, but in the interim you can use Poggu's CS2 docs:

- https://cs2.poggu.me/dumped-data/command-list
- https://cs2.poggu.me/dumped-data/convar-list

**Comment by SuGolYolLom** [comment]
@ArmynC 
Managed to dump the console to a file

Launch options: `-insecure -condebug -conclearlog -console`
Launch cs2 and check the folder: `steamapps\common\Counter-Strike Global Offensive\game\csgo\addons` for a `console.log` file.
 
Use the command `log_dumpchannels` to check channels flags

example:
> \> log_dumpchannels
[Console] ID      Channel Name                        Severity      Color         Flags                               Tags                            
[Console] ----------------------------------------------------------------------------------------------------------------------------------------------------
[Console] 0       LOADING                             default       0x00000000                                                                        
[Console] 1       General                             default       0x00000000                                                                        
[Console] 2       Assert                              default       0x00000000                                                                        
[Console] 3       Console                             default       0x00000000    [ConsoleOnly]                       [Console]                       
[Console] 4       Developer                           essential     0x00000000    [ConsoleOnly]                       [Developer]                     
[Console] 5       DeveloperConsole                    essential     0x00000000    [ConsoleOnly]                       [Console][DeveloperVerbose]     
[Console] 6       DeveloperVerbose                    essential     0xC080C0FF    [ConsoleOnly]                       [DeveloperVerbose]              
[Console] 7       Symbols                             essential     0x00000000                                                                        
...
[Console] 23      ServerLog                           default       0x00000000    [DoNotEcho]                                                         
...
[Console] 73      SoundSystemLowLevel                 default       0xFD9B3BFF                                                                        
[Console] 74      SoundOperatorSystem                 default       0x00000000    [ConsoleOnly]                       [SoundOperatorSystem]           
[Console] 75      SoundSystem                         default       0xFD9B3BFF                                                                        
[Console] 76      SndOperators                        default       0x00000000    [ConsoleOnly]                       [SND][SndOperators]             
[Console] 77      SteamAudio                          default       0xC0C00AFF                                                                        
...
[Console] 89      PanoramaScript                      default       0xC8FFFFFF                                                                        
[Console] 90      Workshop                            default       0x00FFFFFF    [DoNotEcho]                                                         
...
[Console] 106     SndEmitterSystem                    default       0x00000000    [ConsoleOnly]                       [SndEmitterSystem]              
[Console] 107     Wearable                            default       0x00FFFFFF                                                                        
[Console] 108     SteamUnifiedMessages                essential     0xFF8080FF                                        [Steam]                         
[Console] 109     GCClient                            default       0x00000000                                                                        
...
[Console] 121     CSGO game instructor                off           0x00000000                                                                        
[Console] 122     Matchmaking                         off           0x00000000    [ConsoleOnly]                                                       
[Console] 123     RenderPipelineCsgo                  default       0x00000000                                                                        
...

Now its necessary to **remove** `ConsoleOnly` **flag** from some Channels

For that execute the commands:
```
log_flags Console -ConsoleOnly
log_flags Developer -ConsoleOnly
log_flags DeveloperConsole -ConsoleOnly
log_flags DeveloperVerbose -ConsoleOnly
```
* For `cvarlist` => `log_flags Console -ConsoleOnly`

Execute `cvarlist`, `cvar_unhide`, `cvarlist` and **exit the game**

After that, open the file: `steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\console.log`

**Comment by armync** [comment]
Yep, I can confirm that. It is fully functional with the set flags.

![Screenshot 2023-09-09 165418](https://github.com/saul/cvar-unhide-s2/assets/16375271/be262809-6290-49b8-94df-51c0f8a23970)


![Screenshot 2023-09-09 165910](https://github.com/saul/cvar-unhide-s2/assets/16375271/288fe95b-f82c-42b1-9bf5-290fc25c9800)

**Comment by armync** [comment]
Update: Unable to extract defensive commands. I'll check if it is caused by "DefensiveConCommands" set true or if due to addons unable to read them (flag nedded?).

Update2: Defensive not unhidden & logging even with the flag set to zero in .gi

**Comment by armync** [comment]
Right now, the outputed cvars are not the default ones. Any self modified cvar value is outputed as such.

**Comment by saul** [comment]
v0.2.0 has a `cvarlist_md` command that dumps all cvars/concommands. See https://github.com/saul/cvar-unhide-s2/blob/main/cvarlist.md for example output.
