### ISSUE TITLE
It's not unhiding everything

### ISSUE THREAD

**Issue by karl-police** [saul/cvar-unhide-s2#5]
https://cs2.poggu.me/dumped-data/convar-list/

Tried to search for ``net_showmessages`` but it's not unhidden it doesn't do anything in-game

**Comment by karl-police** [comment]
DefensiveConCommands in csgo_core 😊

**Comment by saul** [comment]
This is no longer necessary with v0.2.0

**Comment by karl-police** [comment]
What about those "menubar_item" commands?

**Comment by saul** [comment]
This plugin doesn't have the string for the `menubar_item` flag, but the concmds will still be listed in `cvarlist_md`.

I just released [v0.3.0](https://github.com/saul/cvar-unhide-s2/releases/tag/v0.3.0) which fixes cvarlist not showing hidden cvars. [cvarlist.md](https://github.com/saul/cvar-unhide-s2/blob/main/cvarlist.md) now has `net_showmsg`, as your original issue asked.

**Comment by karl-police** [comment]
What I wonder is, if the menubar_item commands actually still exist or not
